### ISSUE TITLE
Issue with listing mutations using DepMap data 23Q4

### ISSUE THREAD

**Issue by RachelSmid** [ytakemon/GRETTA#38]
Used: 

list_mutations(gene = "KRAS",
               is_hotspot = TRUE, 
               data_dir = gretta_data_dir)%>%
  select(Hugo_Symbol, ProteinChange)

and got the error 

Error in `.data$Annotation_Transcript`:
! Column `Annotation_Transcript` not found in `.data`.

Using GRETTA version 2.5.0

**Comment by ytakemon** [comment]
Updating your `tidyverse` package should do the trick
